### ISSUE TITLE
GitHub release?

### ISSUE THREAD

**Issue by baimafeima** [mbaeuerle/Briss-2.0#12]
I am looking forward to seeing new releases here on GitHub. When can 2.0 be expected?

**Comment by euoar** [comment]
That would indeed be very appreciated. We can't package briss for Solus Linux until it has a release... Thanks for opening this issue @baimafeima  :)

**Comment by baimafeima** [comment]
@mbaeuerle Any chance you could also tag the releases for Briss-2.0?

**Comment by mbaeuerle** [comment]
Sorry for the delay. There is no CI yet, but I created a release [here](https://github.com/mbaeuerle/Briss-2.0/releases/tag/v2.0-alpha).
