### ISSUE TITLE
Briss fails to fully load document

### ISSUE THREAD

**Issue by R2D5connectingx** [mbaeuerle/Briss-2.0#28]
This is not strictly related to the 2.0 overhaul:
I've been using Briss for years - and frequently ran into the problem of pdf-files not fully loading when 'Load file' is selected. - Helped myself by splitting up the pdf into many and processed them individually. Does somebody have a better solution or know what causes this?
Thank you very much!

**Comment by R2D5connectingx** [comment]
Self-update: this had been an issue on various machines for years: 
Just updated JAVA from 6 to 8 on one machine and Briss 0.9 fully loaded the document!

**Comment by mbaeuerle** [comment]
Hi @R2D5connectingx happy to hear that updating Java helped with opening the file.
It could be that the default heap size (the amount of memory the application can use) has changed between versions.
If you still want to try running Briss with Java 6 (just possible with Briss 0.9) and are familiar with the command line you could try to start Briss from there with more memory like so:
```
java -Xmx2g -jar briss-0.9.jar 
```
Also possible errors will be printed in the command line window.
