### ISSUE TITLE
UI without page merging?

### ISSUE THREAD

**Issue by sebsilas** [mbaeuerle/Briss-2.0#29]
Hello,

It doesn't seem to be possible, but I would like to check; is it possible to disable the page merging feature?

I would like to open a PDF, see all the pages (rather than them collapsed/merged), and individually chose regions to export on each page (i.e there is no uniform feature to the cropping I need to do).

This would be really useful.

Thanks,
S

**Comment by mbaeuerle** [comment]
Hi,

unfortunately currently this is not possible in Briss 2.0. In the previous version you could exclude pages from the unified merge panel so each showed up as a single page. But in your case you'd have to manually exclude all pages to be able to crop them individually.

Hope that helps!
