### ISSUE TITLE
Add feature to exclude pages again

### ISSUE THREAD

**Issue by mbaeuerle** [mbaeuerle/Briss-2.0#40]
Currently in Briss 2.0 there is no way to exclude pages like it was possible in the classic Briss 0.9.
As a first step it might be enough to just have an input field in the main Gui where excluded pages can be set.

**Comment by cleydyr** [comment]
What does it mean exactly for a page to be excluded? Is it that the final PDF won't contain the page or that it can't be cropped?

**Comment by GitHubRulesOK** [comment]
Hmm
 "skip" was an odd nom de plume as using say "skip 1" v0.9 cropped the cover independent of other pages (so more like split crops about 1)
![image](https://user-images.githubusercontent.com/12754913/184725486-826f04c6-4058-4936-8888-c122f23ce36f.png)

**Comment by cleydyr** [comment]
Closing as #58 has been merged.
