### ISSUE TITLE
Crop rectangle disappears

### ISSUE THREAD

**Issue by mbaeuerle** [mbaeuerle/Briss-2.0#5]
The crop rectangle disappears if it has negative width and height. This happens if the handle at the top left is dragged over the handle at the bottom right.

**Comment by cleydyr** [comment]
No longer reproducible in master (ef5f14a2461e006774f773bad73a45e38e322afe).

**Comment by mbaeuerle** [comment]
@cleydyr yes you're right, the exact problem doesn't occur any longer. There was still an issue with resizing which moved the rectangle when the width / height was zero. I fixed that now.
