### ISSUE TITLE
Image to big

### ISSUE THREAD

**Issue by maticahacic** [mbaeuerle/Briss-2.0#52]
When I try to open a pdf I get Image to Big error.

![Screenshot from 2022-09-24 11-05-57](https://user-images.githubusercontent.com/25854455/192089877-50c0d342-66ed-4d96-a7bb-4c86b05d0da9.png)

Might be related to this issue - https://github.com/danmbox/briss2/issues/5

**Comment by cleydyr** [comment]
Hey, @maticahacic . Thank you for opening this issue.

Can you share an example PDF with which we can reproduce the behavior?

**Comment by mbaeuerle** [comment]
Hey @maticahacic thanks for bringing this up, and also thanks for pointing to the related issue!
Seems like this is directly related to the PDF size. I could reproduce that with this [Din A0 PDF](https://github.com/mbaeuerle/Briss-2.0/files/9639008/Untitled.pdf) (just white no content in case you're wondering). Let me check what we can do here!

**Comment by maticahacic** [comment]
Great to hear about this!
