### ISSUE TITLE
Add Java 19 support

### ISSUE THREAD

**Issue by cleydyr** [mbaeuerle/Briss-2.0#61]

**Comment by odysseus90210** [comment]
So what is supported?

**Comment by cleydyr** [comment]
Given the description of the README of this project, I'd expect Briss 2.0 to run on Java 8 onwards, including Java 19. But I discovered that Briss 2.0 currently can't run on Java 19. That's why I opened this issue. Until then you'll have to use any of the previous versions of Java which are newer than 8. If you find any problem running the program according to the README instructions, then let us know so that we can fix it eventually.

**Comment by mbaeuerle** [comment]
With the removal of JavaFX the new version also works directly with Java 19: https://github.com/mbaeuerle/Briss-2.0/releases/tag/v2.0-alpha-5
