### ISSUE TITLE
Can't get Briss 2.0 to run without freezing

### ISSUE THREAD

**Issue by odysseus90210** [mbaeuerle/Briss-2.0#64]
Freezes no matter what pdf I feed it. 

Briss 0.9 was easy to use, but 2.0 is a nightmare. Please release a version that includes the JRE!
[Log.txt](https://github.com/mbaeuerle/Briss-2.0/files/11092511/Log.txt)

**Comment by mbaeuerle** [comment]
We had some issues with a JavaFX lib. This is now removed, give it a try with the new version here: https://github.com/mbaeuerle/Briss-2.0/releases/tag/v2.0-alpha-5
I'll close this for now, as including a JRE is not on the roadmap at the moment. Let us know if you still have issues with the new version though!
