### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by sypianski** [mbaeuerle/Briss-2.0#67]
I downloaded the files, I tried clicking on some of them, but the program didn't start. The „Installation” section in the manual is not about installation, but about something else. I've been using Briss 0.9 for years and all I needed to do was to download it and open `briss-0.9.jar`. There's no such file in Briss 2.0 or I can't see it.

If I need to learn something to run in, could you help me by telling what this skill/action/process is? I don't even know what to put in my search engine. The manual seems to run on an assumption that it's obvious to everyone.

**Comment by wilkohardenberg** [comment]
I have the same problem: when I follow the instructions I only get error messages for lack of dependencies.

**Comment by sypianski** [comment]
It’s not the same. I don’t know where to start.

Z pozdrowieniami,
Jakub Sypiański
Il 26.04.2023, 11:24 +0100, Wilko Hardenberg ***@***.***>, ha scritto:

**Comment by wilkohardenberg** [comment]
Have you tried downloading one of the releases (https://github.com/mbaeuerle/Briss-2.0/releases), instead of going from source (as described in the installation instructions)?

**Comment by sypianski** [comment]
I downloaded `Briss-2.0.zip`. I tried clicking on different files after unpacking, but it looks like it's not doing anything.

As for the [installation instructions](https://github.com/mbaeuerle/Briss-2.0#installation), they say only the following:

> Currently Briss 2.0 is in alpha therefore some features are still missing (for example the page skip list). If you want to give it a try you can download the pre release from https://github.com/mbaeuerle/Briss-2.0/releases. There is a version of Briss for Java 8 and one version for any newer version of Java.

There result I still don't know where to start.

**Comment by cleydyr** [comment]
Hey, @sypianski . What is your operating system and Java version?

**Comment by sypianski** [comment]
macOS Ventura 13.3.1 and Java bulid 1.8.0_371-b11

**Comment by cleydyr** [comment]
Hey, @sypianski. Are you using [the Java 8](https://github.com/mbaeuerle/Briss-2.0/releases/download/v2.0-alpha-4/Briss-2.0-java-8.zip) release available on the releases page?

**Comment by sypianski** [comment]
@cleydyr: Yes, I am.

**Comment by cleydyr** [comment]
Here's what I did on a **clean** MacOS Ventura 13.3.1 (22E261) running on a Parallels Desktop virtual machine.

Installed Java 8 for Mac OS x64 from the official site:

```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

Downloaded the Java 8 version from the releases page and extracted its contents.

Run `./bin/Briss-2.0` from the `Briss-2.0` folder:
```
WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
Warning: the font "Times" is not available, so "Lucida Bright" has been substituted, but may have unexpected appearance or behavor. Re-enable the "Times" font to remove this warning.
```

The program opens with no errors.

On the other hand, if I deliberately use the non-java-8 release, I get this:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: at/laborg/briss/Briss has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by cleydyr** [comment]
@sypianski . According to [this post](https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers), it looks like you're trying to run the non-java-8 release with a Java 16 runtime. I'd double-check if you're using Java 8 as the runtime when running the Briss-2.0 script from the command line, as shown in the README file.

**Comment by mbaeuerle** [comment]
@sypianski please check out a new version [here](https://github.com/mbaeuerle/Briss-2.0/releases/tag/v2.0-alpha-5) which simplifies things in regards to Java versions. Hopefully there you are able to either run the script or jar either via shell or double click.

**Comment by mbaeuerle** [comment]
Closing this for now. If there are still issues let us know!

**Comment by sypianski** [comment]
Oh wow, the new release worked out of the box. Thank you!
