### ISSUE TITLE
Can't execute Briss 2.0 on Windows 11 

### ISSUE THREAD

**Issue by cleydyr** [mbaeuerle/Briss-2.0#68]
Windows 11 Home
21H2 (22000.613)

Java version
```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

Execute Briss-2.0.bat and get the following stacktrace:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
        at at.laborg.briss.BrissGUI.<init>(BrissGUI.java:148)
        at at.laborg.briss.Briss.main(Briss.java:34)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more
```

**Comment by mbaeuerle** [comment]
This JavaFX is giving us much trouble and headache. It was just added because the Swing file chooser is not native and looks very ugly IMO.
But it seems like the old AWT FileDialog is native and at least at the moment still works (this needs to be verified for Linux and Win 10 / 11). I'll create a PR for that + a build maybe you can test if that works with Win 11?

**Comment by mbaeuerle** [comment]
@cleydyr please check out the new version [here](https://github.com/mbaeuerle/Briss-2.0/releases/tag/v2.0-alpha-5) which possibly works again with Win 11

**Comment by cleydyr** [comment]
With JRE 8, yes. But not with JRE 18.

**Comment by mbaeuerle** [comment]
So what's the error for JRE 18?

**Comment by cleydyr** [comment]
There's no error. But never mind.

Checking it further, I saw that the window's position was outside the screen, so that I couldn't see it. So no bug here, but ensuring the window appears on (0,0) to override any fancy JVM's defaults would be interesting.

**Comment by mbaeuerle** [comment]
Interesting, I also observed on Windows 10 that the Briss window was opened on the bottom right. I thought it should be centered. Would be also nice to store the previous position and size as user config somewhere (and while we're at it also the previously chosen file paths).

**Comment by cleydyr** [comment]
Opened https://github.com/mbaeuerle/Briss-2.0/issues/70 to track your suggestion.

**Comment by cleydyr** [comment]
>  I also observed on Windows 10 that the Briss window was opened on the bottom right
Found root cause. See https://github.com/mbaeuerle/Briss-2.0/issues/72
