### ISSUE TITLE
How to run on Windows?

### ISSUE THREAD

**Issue by Shohreh** [mbaeuerle/Briss-2.0#83]
Hello,

Contrary to what the [documentation](https://github.com/mbaeuerle/Briss-2.0/blob/master/README.md) says, after clicking on Code and downloading the ZIP file… there's no ./lib/Briss-2.0-all.jar, and no ./bin directory at all.

How to run Bliss on Windows?

Do I need to compile the source with the JDK? Is there no ready-to-use binary distribution?

Thank you.

**Comment by cleydyr** [comment]
Just for the record, the [documentation](https://github.com/mbaeuerle/Briss-2.0/blob/master/README.md) reads:

> If you want to give it a try you can download the pre release from https://github.com/mbaeuerle/Briss-2.0/releases.

I confirm that downloading the pre release as instructed in the documentation and extracting the its ZIP file will give users the lib and bin folders.

**Comment by mbaeuerle** [comment]
Also for the record, I've deleted a comment with a link to a download on a third party website.
